//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LfmSqliteEdm", "ArtistTrack", "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMspider.EDM.Artist), "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMspider.EDM.Track))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LfmSqliteEdm", "TrackSimilarTrack", "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMspider.EDM.Track), "SimilarTrack", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMspider.EDM.SimilarTrack))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LfmSqliteEdm", "TrackSimilarTrack1", "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMspider.EDM.Track), "SimilarTrack", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMspider.EDM.SimilarTrack))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LfmSqliteEdm", "TrackInfoMbid", "TrackInfo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMspider.EDM.TrackInfo), "Mbid", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMspider.EDM.Mbid))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LfmSqliteEdm", "TrackInfoMbid1", "TrackInfo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMspider.EDM.TrackInfo), "Mbid", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMspider.EDM.Mbid))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LfmSqliteEdm", "TagTrackTag", "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMspider.EDM.Tag), "TrackTag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMspider.EDM.TrackTag))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("LfmSqliteEdm", "TrackTrackTag", "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMspider.EDM.Track), "TrackTag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMspider.EDM.TrackTag))]

// Original file name:
// Generation date: 2008-09-18 13:43:43
namespace LastFMspider.EDM
{
    
    /// <summary>
    /// There are no comments for LfmSqliteEdmContainer in the schema.
    /// </summary>
    public partial class LfmSqliteEdmContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new LfmSqliteEdmContainer object using the connection string found in the 'LfmSqliteEdmContainer' section of the application configuration file.
        /// </summary>
        public LfmSqliteEdmContainer() : 
                base("name=LfmSqliteEdmContainer", "LfmSqliteEdmContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LfmSqliteEdmContainer object.
        /// </summary>
        public LfmSqliteEdmContainer(string connectionString) : 
                base(connectionString, "LfmSqliteEdmContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LfmSqliteEdmContainer object.
        /// </summary>
        public LfmSqliteEdmContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "LfmSqliteEdmContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ArtistSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Artist> ArtistSet
        {
            get
            {
                if ((this._ArtistSet == null))
                {
                    this._ArtistSet = base.CreateQuery<Artist>("[ArtistSet]");
                }
                return this._ArtistSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Artist> _ArtistSet;
        /// <summary>
        /// There are no comments for Mbid in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Mbid> Mbid
        {
            get
            {
                if ((this._Mbid == null))
                {
                    this._Mbid = base.CreateQuery<Mbid>("[Mbid]");
                }
                return this._Mbid;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Mbid> _Mbid;
        /// <summary>
        /// There are no comments for SimilarTrackSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SimilarTrack> SimilarTrackSet
        {
            get
            {
                if ((this._SimilarTrackSet == null))
                {
                    this._SimilarTrackSet = base.CreateQuery<SimilarTrack>("[SimilarTrackSet]");
                }
                return this._SimilarTrackSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SimilarTrack> _SimilarTrackSet;
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Tag> Tag
        {
            get
            {
                if ((this._Tag == null))
                {
                    this._Tag = base.CreateQuery<Tag>("[Tag]");
                }
                return this._Tag;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tag> _Tag;
        /// <summary>
        /// There are no comments for TrackSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Track> TrackSet
        {
            get
            {
                if ((this._TrackSet == null))
                {
                    this._TrackSet = base.CreateQuery<Track>("[TrackSet]");
                }
                return this._TrackSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Track> _TrackSet;
        /// <summary>
        /// There are no comments for TrackInfo in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TrackInfo> TrackInfo
        {
            get
            {
                if ((this._TrackInfo == null))
                {
                    this._TrackInfo = base.CreateQuery<TrackInfo>("[TrackInfo]");
                }
                return this._TrackInfo;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TrackInfo> _TrackInfo;
        /// <summary>
        /// There are no comments for TrackTag in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TrackTag> TrackTag
        {
            get
            {
                if ((this._TrackTag == null))
                {
                    this._TrackTag = base.CreateQuery<TrackTag>("[TrackTag]");
                }
                return this._TrackTag;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TrackTag> _TrackTag;
        /// <summary>
        /// There are no comments for ArtistSet in the schema.
        /// </summary>
        public void AddToArtistSet(Artist artist)
        {
            base.AddObject("ArtistSet", artist);
        }
        /// <summary>
        /// There are no comments for Mbid in the schema.
        /// </summary>
        public void AddToMbid(Mbid mbid)
        {
            base.AddObject("Mbid", mbid);
        }
        /// <summary>
        /// There are no comments for SimilarTrackSet in the schema.
        /// </summary>
        public void AddToSimilarTrackSet(SimilarTrack similarTrack)
        {
            base.AddObject("SimilarTrackSet", similarTrack);
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        public void AddToTag(Tag tag)
        {
            base.AddObject("Tag", tag);
        }
        /// <summary>
        /// There are no comments for TrackSet in the schema.
        /// </summary>
        public void AddToTrackSet(Track track)
        {
            base.AddObject("TrackSet", track);
        }
        /// <summary>
        /// There are no comments for TrackInfo in the schema.
        /// </summary>
        public void AddToTrackInfo(TrackInfo trackInfo)
        {
            base.AddObject("TrackInfo", trackInfo);
        }
        /// <summary>
        /// There are no comments for TrackTag in the schema.
        /// </summary>
        public void AddToTrackTag(TrackTag trackTag)
        {
            base.AddObject("TrackTag", trackTag);
        }
    }
    /// <summary>
    /// There are no comments for LfmSqliteEdm.Artist in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ArtistID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LfmSqliteEdm", Name="Artist")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Artist : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Artist object.
        /// </summary>
        /// <param name="artistID">Initial value of ArtistID.</param>
        /// <param name="fullArtist">Initial value of FullArtist.</param>
        /// <param name="lowercaseArtist">Initial value of LowercaseArtist.</param>
        public static Artist CreateArtist(int artistID, string fullArtist, string lowercaseArtist)
        {
            Artist artist = new Artist();
            artist.ArtistID = artistID;
            artist.FullArtist = fullArtist;
            artist.LowercaseArtist = lowercaseArtist;
            return artist;
        }
        /// <summary>
        /// There are no comments for Property ArtistID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistID
        {
            get
            {
                return this._ArtistID;
            }
            set
            {
                this.OnArtistIDChanging(value);
                this.ReportPropertyChanging("ArtistID");
                this._ArtistID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ArtistID");
                this.OnArtistIDChanged();
            }
        }
        private int _ArtistID;
        partial void OnArtistIDChanging(int value);
        partial void OnArtistIDChanged();
        /// <summary>
        /// There are no comments for Property FullArtist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FullArtist
        {
            get
            {
                return this._FullArtist;
            }
            set
            {
                this.OnFullArtistChanging(value);
                this.ReportPropertyChanging("FullArtist");
                this._FullArtist = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FullArtist");
                this.OnFullArtistChanged();
            }
        }
        private string _FullArtist;
        partial void OnFullArtistChanging(string value);
        partial void OnFullArtistChanged();
        /// <summary>
        /// There are no comments for Property LowercaseArtist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LowercaseArtist
        {
            get
            {
                return this._LowercaseArtist;
            }
            set
            {
                this.OnLowercaseArtistChanging(value);
                this.ReportPropertyChanging("LowercaseArtist");
                this._LowercaseArtist = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LowercaseArtist");
                this.OnLowercaseArtistChanged();
            }
        }
        private string _LowercaseArtist;
        partial void OnLowercaseArtistChanging(string value);
        partial void OnLowercaseArtistChanged();
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "ArtistTrack", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Track> Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Track>("LfmSqliteEdm.ArtistTrack", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Track>("LfmSqliteEdm.ArtistTrack", "Track", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LfmSqliteEdm.Mbid in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MbidID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LfmSqliteEdm", Name="Mbid")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Mbid : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Mbid object.
        /// </summary>
        /// <param name="mbidID">Initial value of MbidID.</param>
        /// <param name="lowercaseMbid">Initial value of LowercaseMbid.</param>
        public static Mbid CreateMbid(int mbidID, string lowercaseMbid)
        {
            Mbid mbid = new Mbid();
            mbid.MbidID = mbidID;
            mbid.LowercaseMbid = lowercaseMbid;
            return mbid;
        }
        /// <summary>
        /// There are no comments for Property MbidID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MbidID
        {
            get
            {
                return this._MbidID;
            }
            set
            {
                this.OnMbidIDChanging(value);
                this.ReportPropertyChanging("MbidID");
                this._MbidID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MbidID");
                this.OnMbidIDChanged();
            }
        }
        private int _MbidID;
        partial void OnMbidIDChanging(int value);
        partial void OnMbidIDChanged();
        /// <summary>
        /// There are no comments for Property LowercaseMbid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LowercaseMbid
        {
            get
            {
                return this._LowercaseMbid;
            }
            set
            {
                this.OnLowercaseMbidChanging(value);
                this.ReportPropertyChanging("LowercaseMbid");
                this._LowercaseMbid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LowercaseMbid");
                this.OnLowercaseMbidChanged();
            }
        }
        private string _LowercaseMbid;
        partial void OnLowercaseMbidChanging(string value);
        partial void OnLowercaseMbidChanged();
        /// <summary>
        /// There are no comments for TrackInfo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackInfoMbid", "TrackInfo")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TrackInfo> TrackInfo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TrackInfo>("LfmSqliteEdm.TrackInfoMbid", "TrackInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TrackInfo>("LfmSqliteEdm.TrackInfoMbid", "TrackInfo", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TrackInfo_1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackInfoMbid1", "TrackInfo")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TrackInfo> TrackInfo_1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TrackInfo>("LfmSqliteEdm.TrackInfoMbid1", "TrackInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TrackInfo>("LfmSqliteEdm.TrackInfoMbid1", "TrackInfo", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LfmSqliteEdm.SimilarTrack in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SimilarTrackID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LfmSqliteEdm", Name="SimilarTrack")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SimilarTrack : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SimilarTrack object.
        /// </summary>
        /// <param name="similarTrackID">Initial value of SimilarTrackID.</param>
        /// <param name="rating">Initial value of Rating.</param>
        public static SimilarTrack CreateSimilarTrack(int similarTrackID, float rating)
        {
            SimilarTrack similarTrack = new SimilarTrack();
            similarTrack.SimilarTrackID = similarTrackID;
            similarTrack.Rating = rating;
            return similarTrack;
        }
        /// <summary>
        /// There are no comments for Property SimilarTrackID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SimilarTrackID
        {
            get
            {
                return this._SimilarTrackID;
            }
            set
            {
                this.OnSimilarTrackIDChanging(value);
                this.ReportPropertyChanging("SimilarTrackID");
                this._SimilarTrackID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SimilarTrackID");
                this.OnSimilarTrackIDChanged();
            }
        }
        private int _SimilarTrackID;
        partial void OnSimilarTrackIDChanging(int value);
        partial void OnSimilarTrackIDChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public float Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private float _Rating;
        partial void OnRatingChanging(float value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for A in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackSimilarTrack", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track A
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack", "Track").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack", "Track").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for A in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> AReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack", "Track", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for B in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackSimilarTrack1", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track B
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack1", "Track").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack1", "Track").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for B in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> BReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack1", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("LfmSqliteEdm.TrackSimilarTrack1", "Track", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LfmSqliteEdm.Tag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LfmSqliteEdm", Name="Tag")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tag : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tagID">Initial value of TagID.</param>
        /// <param name="lowercaseTag">Initial value of LowercaseTag.</param>
        public static Tag CreateTag(int tagID, string lowercaseTag)
        {
            Tag tag = new Tag();
            tag.TagID = tagID;
            tag.LowercaseTag = lowercaseTag;
            return tag;
        }
        /// <summary>
        /// There are no comments for Property TagID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TagID
        {
            get
            {
                return this._TagID;
            }
            set
            {
                this.OnTagIDChanging(value);
                this.ReportPropertyChanging("TagID");
                this._TagID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagID");
                this.OnTagIDChanged();
            }
        }
        private int _TagID;
        partial void OnTagIDChanging(int value);
        partial void OnTagIDChanged();
        /// <summary>
        /// There are no comments for Property LowercaseTag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LowercaseTag
        {
            get
            {
                return this._LowercaseTag;
            }
            set
            {
                this.OnLowercaseTagChanging(value);
                this.ReportPropertyChanging("LowercaseTag");
                this._LowercaseTag = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LowercaseTag");
                this.OnLowercaseTagChanged();
            }
        }
        private string _LowercaseTag;
        partial void OnLowercaseTagChanging(string value);
        partial void OnLowercaseTagChanged();
        /// <summary>
        /// There are no comments for TrackTag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TagTrackTag", "TrackTag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TrackTag> TrackTag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TrackTag>("LfmSqliteEdm.TagTrackTag", "TrackTag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TrackTag>("LfmSqliteEdm.TagTrackTag", "TrackTag", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LfmSqliteEdm.Track in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TrackID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LfmSqliteEdm", Name="Track")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Track : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Track object.
        /// </summary>
        /// <param name="trackID">Initial value of TrackID.</param>
        /// <param name="fullTitle">Initial value of FullTitle.</param>
        /// <param name="lowercaseTitle">Initial value of LowercaseTitle.</param>
        public static Track CreateTrack(int trackID, string fullTitle, string lowercaseTitle)
        {
            Track track = new Track();
            track.TrackID = trackID;
            track.FullTitle = fullTitle;
            track.LowercaseTitle = lowercaseTitle;
            return track;
        }
        /// <summary>
        /// There are no comments for Property TrackID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackID
        {
            get
            {
                return this._TrackID;
            }
            set
            {
                this.OnTrackIDChanging(value);
                this.ReportPropertyChanging("TrackID");
                this._TrackID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TrackID");
                this.OnTrackIDChanged();
            }
        }
        private int _TrackID;
        partial void OnTrackIDChanging(int value);
        partial void OnTrackIDChanged();
        /// <summary>
        /// There are no comments for Property FullTitle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FullTitle
        {
            get
            {
                return this._FullTitle;
            }
            set
            {
                this.OnFullTitleChanging(value);
                this.ReportPropertyChanging("FullTitle");
                this._FullTitle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FullTitle");
                this.OnFullTitleChanged();
            }
        }
        private string _FullTitle;
        partial void OnFullTitleChanging(string value);
        partial void OnFullTitleChanged();
        /// <summary>
        /// There are no comments for Property LowercaseTitle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LowercaseTitle
        {
            get
            {
                return this._LowercaseTitle;
            }
            set
            {
                this.OnLowercaseTitleChanging(value);
                this.ReportPropertyChanging("LowercaseTitle");
                this._LowercaseTitle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LowercaseTitle");
                this.OnLowercaseTitleChanged();
            }
        }
        private string _LowercaseTitle;
        partial void OnLowercaseTitleChanging(string value);
        partial void OnLowercaseTitleChanged();
        /// <summary>
        /// There are no comments for Property LookupTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> LookupTimestamp
        {
            get
            {
                return this._LookupTimestamp;
            }
            set
            {
                this.OnLookupTimestampChanging(value);
                this.ReportPropertyChanging("LookupTimestamp");
                this._LookupTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LookupTimestamp");
                this.OnLookupTimestampChanged();
            }
        }
        private global::System.Nullable<long> _LookupTimestamp;
        partial void OnLookupTimestampChanging(global::System.Nullable<long> value);
        partial void OnLookupTimestampChanged();
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "ArtistTrack", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Artist Artist
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("LfmSqliteEdm.ArtistTrack", "Artist").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("LfmSqliteEdm.ArtistTrack", "Artist").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Artist> ArtistReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("LfmSqliteEdm.ArtistTrack", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Artist>("LfmSqliteEdm.ArtistTrack", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for SimilarTrack in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackSimilarTrack", "SimilarTrack")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarTrack> SimilarTrack
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarTrack>("LfmSqliteEdm.TrackSimilarTrack", "SimilarTrack");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarTrack>("LfmSqliteEdm.TrackSimilarTrack", "SimilarTrack", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for SimilarTrack_1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackSimilarTrack1", "SimilarTrack")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarTrack> SimilarTrack_1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarTrack>("LfmSqliteEdm.TrackSimilarTrack1", "SimilarTrack");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarTrack>("LfmSqliteEdm.TrackSimilarTrack1", "SimilarTrack", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TrackTag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackTrackTag", "TrackTag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TrackTag> TrackTag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TrackTag>("LfmSqliteEdm.TrackTrackTag", "TrackTag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TrackTag>("LfmSqliteEdm.TrackTrackTag", "TrackTag", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LfmSqliteEdm.TrackInfo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TrackID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LfmSqliteEdm", Name="TrackInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TrackInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TrackInfo object.
        /// </summary>
        /// <param name="trackID">Initial value of TrackID.</param>
        /// <param name="infoTimestamp">Initial value of InfoTimestamp.</param>
        public static TrackInfo CreateTrackInfo(int trackID, long infoTimestamp)
        {
            TrackInfo trackInfo = new TrackInfo();
            trackInfo.TrackID = trackID;
            trackInfo.InfoTimestamp = infoTimestamp;
            return trackInfo;
        }
        /// <summary>
        /// There are no comments for Property TrackID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackID
        {
            get
            {
                return this._TrackID;
            }
            set
            {
                this.OnTrackIDChanging(value);
                this.ReportPropertyChanging("TrackID");
                this._TrackID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TrackID");
                this.OnTrackIDChanged();
            }
        }
        private int _TrackID;
        partial void OnTrackIDChanging(int value);
        partial void OnTrackIDChanged();
        /// <summary>
        /// There are no comments for Property InfoTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long InfoTimestamp
        {
            get
            {
                return this._InfoTimestamp;
            }
            set
            {
                this.OnInfoTimestampChanging(value);
                this.ReportPropertyChanging("InfoTimestamp");
                this._InfoTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("InfoTimestamp");
                this.OnInfoTimestampChanged();
            }
        }
        private long _InfoTimestamp;
        partial void OnInfoTimestampChanging(long value);
        partial void OnInfoTimestampChanged();
        /// <summary>
        /// There are no comments for Property Listeners in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Listeners
        {
            get
            {
                return this._Listeners;
            }
            set
            {
                this.OnListenersChanging(value);
                this.ReportPropertyChanging("Listeners");
                this._Listeners = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Listeners");
                this.OnListenersChanged();
            }
        }
        private global::System.Nullable<int> _Listeners;
        partial void OnListenersChanging(global::System.Nullable<int> value);
        partial void OnListenersChanged();
        /// <summary>
        /// There are no comments for Property Playcount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Playcount
        {
            get
            {
                return this._Playcount;
            }
            set
            {
                this.OnPlaycountChanging(value);
                this.ReportPropertyChanging("Playcount");
                this._Playcount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Playcount");
                this.OnPlaycountChanged();
            }
        }
        private global::System.Nullable<int> _Playcount;
        partial void OnPlaycountChanging(global::System.Nullable<int> value);
        partial void OnPlaycountChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this.ReportPropertyChanging("Duration");
                this._Duration = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Duration");
                this.OnDurationChanged();
            }
        }
        private global::System.Nullable<int> _Duration;
        partial void OnDurationChanging(global::System.Nullable<int> value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property LastFmId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> LastFmId
        {
            get
            {
                return this._LastFmId;
            }
            set
            {
                this.OnLastFmIdChanging(value);
                this.ReportPropertyChanging("LastFmId");
                this._LastFmId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastFmId");
                this.OnLastFmIdChanged();
            }
        }
        private global::System.Nullable<int> _LastFmId;
        partial void OnLastFmIdChanging(global::System.Nullable<int> value);
        partial void OnLastFmIdChanged();
        /// <summary>
        /// There are no comments for ArtistMbid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackInfoMbid", "Mbid")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Mbid ArtistMbid
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid", "Mbid").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid", "Mbid").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ArtistMbid in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Mbid> ArtistMbidReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid", "Mbid");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid", "Mbid", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TrackMbid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackInfoMbid1", "Mbid")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Mbid TrackMbid
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid1", "Mbid").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid1", "Mbid").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TrackMbid in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Mbid> TrackMbidReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid1", "Mbid");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Mbid>("LfmSqliteEdm.TrackInfoMbid1", "Mbid", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for LfmSqliteEdm.TrackTag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TrackTagID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="LfmSqliteEdm", Name="TrackTag")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TrackTag : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TrackTag object.
        /// </summary>
        /// <param name="trackTagID">Initial value of TrackTagID.</param>
        /// <param name="tagCount">Initial value of TagCount.</param>
        public static TrackTag CreateTrackTag(int trackTagID, int tagCount)
        {
            TrackTag trackTag = new TrackTag();
            trackTag.TrackTagID = trackTagID;
            trackTag.TagCount = tagCount;
            return trackTag;
        }
        /// <summary>
        /// There are no comments for Property TrackTagID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackTagID
        {
            get
            {
                return this._TrackTagID;
            }
            set
            {
                this.OnTrackTagIDChanging(value);
                this.ReportPropertyChanging("TrackTagID");
                this._TrackTagID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TrackTagID");
                this.OnTrackTagIDChanged();
            }
        }
        private int _TrackTagID;
        partial void OnTrackTagIDChanging(int value);
        partial void OnTrackTagIDChanged();
        /// <summary>
        /// There are no comments for Property TagCount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TagCount
        {
            get
            {
                return this._TagCount;
            }
            set
            {
                this.OnTagCountChanging(value);
                this.ReportPropertyChanging("TagCount");
                this._TagCount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagCount");
                this.OnTagCountChanged();
            }
        }
        private int _TagCount;
        partial void OnTagCountChanging(int value);
        partial void OnTagCountChanged();
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TagTrackTag", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Tag Tag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("LfmSqliteEdm.TagTrackTag", "Tag").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("LfmSqliteEdm.TagTrackTag", "Tag").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Tag> TagReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("LfmSqliteEdm.TagTrackTag", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Tag>("LfmSqliteEdm.TagTrackTag", "Tag", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("LfmSqliteEdm", "TrackTrackTag", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackTrackTag", "Track").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackTrackTag", "Track").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> TrackReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("LfmSqliteEdm.TrackTrackTag", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("LfmSqliteEdm.TrackTrackTag", "Track", value);
                }
            }
        }
    }
}
