require 'rubygems'
require 'activerecord'
require 'yaml'

task :default => :migrate

desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
task :migrate => :environment do
  ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
end

task :environment do
  APP_ROOT = File.dirname(__FILE__) unless defined?(APP_ROOT)
  LOGGER   = Logger.new( File.join(APP_ROOT, "log/migration.log") )

  ### Set up ActiveRecord
  ActiveRecord::Base.establish_connection(
    :adapter => "sqlite3",
    :database => File.join(APP_ROOT, "db/songdb.sqlite3"),
    :timeout => 5000
  )
  
  ActiveRecord::Base.logger = LOGGER
end
