//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_Artist_0", "TopTracksList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LastFMentityModel.TopTracksList), "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.Artist))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_Artist_1", "SimilarArtistList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LastFMentityModel.SimilarArtistList), "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.Artist))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_Artist_2", "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LastFMentityModel.Artist), "Artist1", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.Artist))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_SimilarArtist_1", "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.Artist), "SimilarArtist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.SimilarArtist))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_SimilarArtistList_0", "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.Artist), "SimilarArtistList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.SimilarArtistList))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_TopTracksList_0", "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.Artist), "TopTracksList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.TopTracksList))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_Track_1", "Artist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.Artist), "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.Track))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_SimilarArtist_0", "SimilarArtistList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.SimilarArtistList), "SimilarArtist", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.SimilarArtist))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_SimilarTrack_0", "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.Track), "SimilarTrack", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.SimilarTrack))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_SimilarTrack_1", "SimilarTrackList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.SimilarTrackList), "SimilarTrack", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.SimilarTrack))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_SimilarTrackList_0", "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.Track), "SimilarTrackList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.SimilarTrackList))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_Track_0", "SimilarTrackList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LastFMentityModel.SimilarTrackList), "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.Track))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_TopTracks_0", "Track", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.Track), "TopTracks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.TopTracks))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("lastFMcacheModel", "FK_TopTracks_1", "TopTracksList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LastFMentityModel.TopTracksList), "TopTracks", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LastFMentityModel.TopTracks))]

// Original file name:
// Generation date: 2009-07-17 23:45:03
namespace LastFMentityModel
{
    
    /// <summary>
    /// There are no comments for LastFMCacheModel in the schema.
    /// </summary>
    public partial class LastFMCacheModel : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new LastFMCacheModel object using the connection string found in the 'LastFMCacheModel' section of the application configuration file.
        /// </summary>
        public LastFMCacheModel() : 
                base("name=LastFMCacheModel", "LastFMCacheModel")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LastFMCacheModel object.
        /// </summary>
        public LastFMCacheModel(string connectionString) : 
                base(connectionString, "LastFMCacheModel")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new LastFMCacheModel object.
        /// </summary>
        public LastFMCacheModel(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "LastFMCacheModel")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Artist> Artist
        {
            get
            {
                if ((this._Artist == null))
                {
                    this._Artist = base.CreateQuery<Artist>("[Artist]");
                }
                return this._Artist;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Artist> _Artist;
        /// <summary>
        /// There are no comments for SimilarArtist in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SimilarArtist> SimilarArtist
        {
            get
            {
                if ((this._SimilarArtist == null))
                {
                    this._SimilarArtist = base.CreateQuery<SimilarArtist>("[SimilarArtist]");
                }
                return this._SimilarArtist;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SimilarArtist> _SimilarArtist;
        /// <summary>
        /// There are no comments for SimilarArtistList in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SimilarArtistList> SimilarArtistList
        {
            get
            {
                if ((this._SimilarArtistList == null))
                {
                    this._SimilarArtistList = base.CreateQuery<SimilarArtistList>("[SimilarArtistList]");
                }
                return this._SimilarArtistList;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SimilarArtistList> _SimilarArtistList;
        /// <summary>
        /// There are no comments for SimilarTrack in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SimilarTrack> SimilarTrack
        {
            get
            {
                if ((this._SimilarTrack == null))
                {
                    this._SimilarTrack = base.CreateQuery<SimilarTrack>("[SimilarTrack]");
                }
                return this._SimilarTrack;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SimilarTrack> _SimilarTrack;
        /// <summary>
        /// There are no comments for SimilarTrackList in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SimilarTrackList> SimilarTrackList
        {
            get
            {
                if ((this._SimilarTrackList == null))
                {
                    this._SimilarTrackList = base.CreateQuery<SimilarTrackList>("[SimilarTrackList]");
                }
                return this._SimilarTrackList;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SimilarTrackList> _SimilarTrackList;
        /// <summary>
        /// There are no comments for TopTracks in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TopTracks> TopTracks
        {
            get
            {
                if ((this._TopTracks == null))
                {
                    this._TopTracks = base.CreateQuery<TopTracks>("[TopTracks]");
                }
                return this._TopTracks;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TopTracks> _TopTracks;
        /// <summary>
        /// There are no comments for TopTracksList in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TopTracksList> TopTracksList
        {
            get
            {
                if ((this._TopTracksList == null))
                {
                    this._TopTracksList = base.CreateQuery<TopTracksList>("[TopTracksList]");
                }
                return this._TopTracksList;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TopTracksList> _TopTracksList;
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Track> Track
        {
            get
            {
                if ((this._Track == null))
                {
                    this._Track = base.CreateQuery<Track>("[Track]");
                }
                return this._Track;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Track> _Track;
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        public void AddToArtist(Artist artist)
        {
            base.AddObject("Artist", artist);
        }
        /// <summary>
        /// There are no comments for SimilarArtist in the schema.
        /// </summary>
        public void AddToSimilarArtist(SimilarArtist similarArtist)
        {
            base.AddObject("SimilarArtist", similarArtist);
        }
        /// <summary>
        /// There are no comments for SimilarArtistList in the schema.
        /// </summary>
        public void AddToSimilarArtistList(SimilarArtistList similarArtistList)
        {
            base.AddObject("SimilarArtistList", similarArtistList);
        }
        /// <summary>
        /// There are no comments for SimilarTrack in the schema.
        /// </summary>
        public void AddToSimilarTrack(SimilarTrack similarTrack)
        {
            base.AddObject("SimilarTrack", similarTrack);
        }
        /// <summary>
        /// There are no comments for SimilarTrackList in the schema.
        /// </summary>
        public void AddToSimilarTrackList(SimilarTrackList similarTrackList)
        {
            base.AddObject("SimilarTrackList", similarTrackList);
        }
        /// <summary>
        /// There are no comments for TopTracks in the schema.
        /// </summary>
        public void AddToTopTracks(TopTracks topTracks)
        {
            base.AddObject("TopTracks", topTracks);
        }
        /// <summary>
        /// There are no comments for TopTracksList in the schema.
        /// </summary>
        public void AddToTopTracksList(TopTracksList topTracksList)
        {
            base.AddObject("TopTracksList", topTracksList);
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        public void AddToTrack(Track track)
        {
            base.AddObject("Track", track);
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.Artist in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ArtistID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="Artist")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Artist : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Artist object.
        /// </summary>
        /// <param name="artistID">Initial value of ArtistID.</param>
        /// <param name="fullArtist">Initial value of FullArtist.</param>
        /// <param name="lowercaseArtist">Initial value of LowercaseArtist.</param>
        public static Artist CreateArtist(int artistID, string fullArtist, string lowercaseArtist)
        {
            Artist artist = new Artist();
            artist.ArtistID = artistID;
            artist.FullArtist = fullArtist;
            artist.LowercaseArtist = lowercaseArtist;
            return artist;
        }
        /// <summary>
        /// There are no comments for Property ArtistID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistID
        {
            get
            {
                return this._ArtistID;
            }
            set
            {
                this.OnArtistIDChanging(value);
                this.ReportPropertyChanging("ArtistID");
                this._ArtistID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ArtistID");
                this.OnArtistIDChanged();
            }
        }
        private int _ArtistID;
        partial void OnArtistIDChanging(int value);
        partial void OnArtistIDChanged();
        /// <summary>
        /// There are no comments for Property FullArtist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FullArtist
        {
            get
            {
                return this._FullArtist;
            }
            set
            {
                this.OnFullArtistChanging(value);
                this.ReportPropertyChanging("FullArtist");
                this._FullArtist = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FullArtist");
                this.OnFullArtistChanged();
            }
        }
        private string _FullArtist;
        partial void OnFullArtistChanging(string value);
        partial void OnFullArtistChanged();
        /// <summary>
        /// There are no comments for Property LowercaseArtist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LowercaseArtist
        {
            get
            {
                return this._LowercaseArtist;
            }
            set
            {
                this.OnLowercaseArtistChanging(value);
                this.ReportPropertyChanging("LowercaseArtist");
                this._LowercaseArtist = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LowercaseArtist");
                this.OnLowercaseArtistChanged();
            }
        }
        private string _LowercaseArtist;
        partial void OnLowercaseArtistChanging(string value);
        partial void OnLowercaseArtistChanged();
        /// <summary>
        /// There are no comments for CurrentTopTracksList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Artist_0", "TopTracksList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TopTracksList CurrentTopTracksList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TopTracksList>("lastFMcacheModel.FK_Artist_0", "TopTracksList").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TopTracksList>("lastFMcacheModel.FK_Artist_0", "TopTracksList").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CurrentTopTracksList in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TopTracksList> CurrentTopTracksListReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TopTracksList>("lastFMcacheModel.FK_Artist_0", "TopTracksList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TopTracksList>("lastFMcacheModel.FK_Artist_0", "TopTracksList", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for CurrentSimilarArtistList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Artist_1", "SimilarArtistList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SimilarArtistList CurrentSimilarArtistList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_Artist_1", "SimilarArtistList").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_Artist_1", "SimilarArtistList").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CurrentSimilarArtistList in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SimilarArtistList> CurrentSimilarArtistListReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_Artist_1", "SimilarArtistList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_Artist_1", "SimilarArtistList", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for BadAlternates in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Artist_2", "Artist1")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Artist> BadAlternates
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Artist>("lastFMcacheModel.FK_Artist_2", "Artist1");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Artist>("lastFMcacheModel.FK_Artist_2", "Artist1", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for CorrectAlternate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Artist_2", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Artist CorrectAlternate
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_Artist_2", "Artist").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_Artist_2", "Artist").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CorrectAlternate in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Artist> CorrectAlternateReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_Artist_2", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Artist>("lastFMcacheModel.FK_Artist_2", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for RefSimilarArtistOf in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarArtist_1", "SimilarArtist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarArtist> RefSimilarArtistOf
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarArtist>("lastFMcacheModel.FK_SimilarArtist_1", "SimilarArtist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarArtist>("lastFMcacheModel.FK_SimilarArtist_1", "SimilarArtist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for SimilarArtistLists in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarArtistList_0", "SimilarArtistList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarArtistList> SimilarArtistLists
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarArtistList>("lastFMcacheModel.FK_SimilarArtistList_0", "SimilarArtistList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarArtistList>("lastFMcacheModel.FK_SimilarArtistList_0", "SimilarArtistList", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TopTracksLists in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_TopTracksList_0", "TopTracksList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TopTracksList> TopTracksLists
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TopTracksList>("lastFMcacheModel.FK_TopTracksList_0", "TopTracksList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TopTracksList>("lastFMcacheModel.FK_TopTracksList_0", "TopTracksList", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Track_1", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Track> Tracks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Track>("lastFMcacheModel.FK_Track_1", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Track>("lastFMcacheModel.FK_Track_1", "Track", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.SimilarArtist in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SimilarArtistID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="SimilarArtist")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SimilarArtist : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SimilarArtist object.
        /// </summary>
        /// <param name="similarArtistID">Initial value of SimilarArtistID.</param>
        /// <param name="rating">Initial value of Rating.</param>
        public static SimilarArtist CreateSimilarArtist(int similarArtistID, float rating)
        {
            SimilarArtist similarArtist = new SimilarArtist();
            similarArtist.SimilarArtistID = similarArtistID;
            similarArtist.Rating = rating;
            return similarArtist;
        }
        /// <summary>
        /// There are no comments for Property SimilarArtistID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SimilarArtistID
        {
            get
            {
                return this._SimilarArtistID;
            }
            set
            {
                this.OnSimilarArtistIDChanging(value);
                this.ReportPropertyChanging("SimilarArtistID");
                this._SimilarArtistID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SimilarArtistID");
                this.OnSimilarArtistIDChanged();
            }
        }
        private int _SimilarArtistID;
        partial void OnSimilarArtistIDChanging(int value);
        partial void OnSimilarArtistIDChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public float Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private float _Rating;
        partial void OnRatingChanging(float value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for SimilarToArtist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarArtist_1", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Artist SimilarToArtist
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtist_1", "Artist").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtist_1", "Artist").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for SimilarToArtist in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Artist> SimilarToArtistReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtist_1", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtist_1", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for InList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarArtist_0", "SimilarArtistList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SimilarArtistList InList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_SimilarArtist_0", "SimilarArtistList").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_SimilarArtist_0", "SimilarArtistList").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for InList in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SimilarArtistList> InListReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_SimilarArtist_0", "SimilarArtistList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SimilarArtistList>("lastFMcacheModel.FK_SimilarArtist_0", "SimilarArtistList", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.SimilarArtistList in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ListID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="SimilarArtistList")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SimilarArtistList : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SimilarArtistList object.
        /// </summary>
        /// <param name="listID">Initial value of ListID.</param>
        /// <param name="lookupTimestamp">Initial value of LookupTimestamp.</param>
        public static SimilarArtistList CreateSimilarArtistList(int listID, long lookupTimestamp)
        {
            SimilarArtistList similarArtistList = new SimilarArtistList();
            similarArtistList.ListID = listID;
            similarArtistList.LookupTimestamp = lookupTimestamp;
            return similarArtistList;
        }
        /// <summary>
        /// There are no comments for Property ListID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ListID
        {
            get
            {
                return this._ListID;
            }
            set
            {
                this.OnListIDChanging(value);
                this.ReportPropertyChanging("ListID");
                this._ListID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ListID");
                this.OnListIDChanged();
            }
        }
        private int _ListID;
        partial void OnListIDChanging(int value);
        partial void OnListIDChanged();
        /// <summary>
        /// There are no comments for Property LookupTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long LookupTimestamp
        {
            get
            {
                return this._LookupTimestamp;
            }
            set
            {
                this.OnLookupTimestampChanging(value);
                this.ReportPropertyChanging("LookupTimestamp");
                this._LookupTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LookupTimestamp");
                this.OnLookupTimestampChanged();
            }
        }
        private long _LookupTimestamp;
        partial void OnLookupTimestampChanging(long value);
        partial void OnLookupTimestampChanged();
        /// <summary>
        /// There are no comments for Property StatusCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> StatusCode
        {
            get
            {
                return this._StatusCode;
            }
            set
            {
                this.OnStatusCodeChanging(value);
                this.ReportPropertyChanging("StatusCode");
                this._StatusCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StatusCode");
                this.OnStatusCodeChanged();
            }
        }
        private global::System.Nullable<int> _StatusCode;
        partial void OnStatusCodeChanging(global::System.Nullable<int> value);
        partial void OnStatusCodeChanged();
        /// <summary>
        /// There are no comments for IsCurrentOf in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Artist_1", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Artist> IsCurrentOf
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Artist>("lastFMcacheModel.FK_Artist_1", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Artist>("lastFMcacheModel.FK_Artist_1", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OfArtist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarArtistList_0", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Artist OfArtist
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtistList_0", "Artist").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtistList_0", "Artist").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OfArtist in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Artist> OfArtistReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtistList_0", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Artist>("lastFMcacheModel.FK_SimilarArtistList_0", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for SimilarArtists in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarArtist_0", "SimilarArtist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarArtist> SimilarArtists
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarArtist>("lastFMcacheModel.FK_SimilarArtist_0", "SimilarArtist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarArtist>("lastFMcacheModel.FK_SimilarArtist_0", "SimilarArtist", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.SimilarTrack in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SimilarTrackID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="SimilarTrack")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SimilarTrack : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SimilarTrack object.
        /// </summary>
        /// <param name="similarTrackID">Initial value of SimilarTrackID.</param>
        /// <param name="rating">Initial value of Rating.</param>
        public static SimilarTrack CreateSimilarTrack(int similarTrackID, float rating)
        {
            SimilarTrack similarTrack = new SimilarTrack();
            similarTrack.SimilarTrackID = similarTrackID;
            similarTrack.Rating = rating;
            return similarTrack;
        }
        /// <summary>
        /// There are no comments for Property SimilarTrackID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SimilarTrackID
        {
            get
            {
                return this._SimilarTrackID;
            }
            set
            {
                this.OnSimilarTrackIDChanging(value);
                this.ReportPropertyChanging("SimilarTrackID");
                this._SimilarTrackID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SimilarTrackID");
                this.OnSimilarTrackIDChanged();
            }
        }
        private int _SimilarTrackID;
        partial void OnSimilarTrackIDChanging(int value);
        partial void OnSimilarTrackIDChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public float Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private float _Rating;
        partial void OnRatingChanging(float value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for SimilarToTrack in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarTrack_0", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track SimilarToTrack
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrack_0", "Track").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrack_0", "Track").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for SimilarToTrack in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> SimilarToTrackReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrack_0", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrack_0", "Track", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for InList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarTrack_1", "SimilarTrackList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SimilarTrackList InList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_SimilarTrack_1", "SimilarTrackList").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_SimilarTrack_1", "SimilarTrackList").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for InList in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SimilarTrackList> InListReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_SimilarTrack_1", "SimilarTrackList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_SimilarTrack_1", "SimilarTrackList", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.SimilarTrackList in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ListID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="SimilarTrackList")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SimilarTrackList : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SimilarTrackList object.
        /// </summary>
        /// <param name="listID">Initial value of ListID.</param>
        /// <param name="lookupTimestamp">Initial value of LookupTimestamp.</param>
        public static SimilarTrackList CreateSimilarTrackList(int listID, long lookupTimestamp)
        {
            SimilarTrackList similarTrackList = new SimilarTrackList();
            similarTrackList.ListID = listID;
            similarTrackList.LookupTimestamp = lookupTimestamp;
            return similarTrackList;
        }
        /// <summary>
        /// There are no comments for Property ListID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ListID
        {
            get
            {
                return this._ListID;
            }
            set
            {
                this.OnListIDChanging(value);
                this.ReportPropertyChanging("ListID");
                this._ListID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ListID");
                this.OnListIDChanged();
            }
        }
        private int _ListID;
        partial void OnListIDChanging(int value);
        partial void OnListIDChanged();
        /// <summary>
        /// There are no comments for Property LookupTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long LookupTimestamp
        {
            get
            {
                return this._LookupTimestamp;
            }
            set
            {
                this.OnLookupTimestampChanging(value);
                this.ReportPropertyChanging("LookupTimestamp");
                this._LookupTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LookupTimestamp");
                this.OnLookupTimestampChanged();
            }
        }
        private long _LookupTimestamp;
        partial void OnLookupTimestampChanging(long value);
        partial void OnLookupTimestampChanged();
        /// <summary>
        /// There are no comments for Property StatusCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> StatusCode
        {
            get
            {
                return this._StatusCode;
            }
            set
            {
                this.OnStatusCodeChanging(value);
                this.ReportPropertyChanging("StatusCode");
                this._StatusCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StatusCode");
                this.OnStatusCodeChanged();
            }
        }
        private global::System.Nullable<int> _StatusCode;
        partial void OnStatusCodeChanging(global::System.Nullable<int> value);
        partial void OnStatusCodeChanged();
        /// <summary>
        /// There are no comments for SimilarTracks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarTrack_1", "SimilarTrack")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarTrack> SimilarTracks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarTrack>("lastFMcacheModel.FK_SimilarTrack_1", "SimilarTrack");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarTrack>("lastFMcacheModel.FK_SimilarTrack_1", "SimilarTrack", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarTrackList_0", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrackList_0", "Track").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrackList_0", "Track").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> TrackReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrackList_0", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("lastFMcacheModel.FK_SimilarTrackList_0", "Track", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for IsCurrentOf in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Track_0", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Track> IsCurrentOf
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Track>("lastFMcacheModel.FK_Track_0", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Track>("lastFMcacheModel.FK_Track_0", "Track", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.TopTracks in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TopTrackID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="TopTracks")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TopTracks : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TopTracks object.
        /// </summary>
        /// <param name="topTrackID">Initial value of TopTrackID.</param>
        /// <param name="reach">Initial value of Reach.</param>
        public static TopTracks CreateTopTracks(int topTrackID, int reach)
        {
            TopTracks topTracks = new TopTracks();
            topTracks.TopTrackID = topTrackID;
            topTracks.Reach = reach;
            return topTracks;
        }
        /// <summary>
        /// There are no comments for Property TopTrackID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TopTrackID
        {
            get
            {
                return this._TopTrackID;
            }
            set
            {
                this.OnTopTrackIDChanging(value);
                this.ReportPropertyChanging("TopTrackID");
                this._TopTrackID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TopTrackID");
                this.OnTopTrackIDChanged();
            }
        }
        private int _TopTrackID;
        partial void OnTopTrackIDChanging(int value);
        partial void OnTopTrackIDChanged();
        /// <summary>
        /// There are no comments for Property Reach in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Reach
        {
            get
            {
                return this._Reach;
            }
            set
            {
                this.OnReachChanging(value);
                this.ReportPropertyChanging("Reach");
                this._Reach = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Reach");
                this.OnReachChanged();
            }
        }
        private int _Reach;
        partial void OnReachChanging(int value);
        partial void OnReachChanged();
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_TopTracks_0", "Track")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Track Track
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_TopTracks_0", "Track").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_TopTracks_0", "Track").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Track in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Track> TrackReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Track>("lastFMcacheModel.FK_TopTracks_0", "Track");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Track>("lastFMcacheModel.FK_TopTracks_0", "Track", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for InList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_TopTracks_1", "TopTracksList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TopTracksList InList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TopTracksList>("lastFMcacheModel.FK_TopTracks_1", "TopTracksList").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TopTracksList>("lastFMcacheModel.FK_TopTracks_1", "TopTracksList").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for InList in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TopTracksList> InListReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TopTracksList>("lastFMcacheModel.FK_TopTracks_1", "TopTracksList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TopTracksList>("lastFMcacheModel.FK_TopTracks_1", "TopTracksList", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.TopTracksList in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ListID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="TopTracksList")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TopTracksList : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TopTracksList object.
        /// </summary>
        /// <param name="listID">Initial value of ListID.</param>
        /// <param name="lookupTimestamp">Initial value of LookupTimestamp.</param>
        public static TopTracksList CreateTopTracksList(int listID, long lookupTimestamp)
        {
            TopTracksList topTracksList = new TopTracksList();
            topTracksList.ListID = listID;
            topTracksList.LookupTimestamp = lookupTimestamp;
            return topTracksList;
        }
        /// <summary>
        /// There are no comments for Property ListID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ListID
        {
            get
            {
                return this._ListID;
            }
            set
            {
                this.OnListIDChanging(value);
                this.ReportPropertyChanging("ListID");
                this._ListID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ListID");
                this.OnListIDChanged();
            }
        }
        private int _ListID;
        partial void OnListIDChanging(int value);
        partial void OnListIDChanged();
        /// <summary>
        /// There are no comments for Property LookupTimestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long LookupTimestamp
        {
            get
            {
                return this._LookupTimestamp;
            }
            set
            {
                this.OnLookupTimestampChanging(value);
                this.ReportPropertyChanging("LookupTimestamp");
                this._LookupTimestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LookupTimestamp");
                this.OnLookupTimestampChanged();
            }
        }
        private long _LookupTimestamp;
        partial void OnLookupTimestampChanging(long value);
        partial void OnLookupTimestampChanged();
        /// <summary>
        /// There are no comments for Property StatusCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> StatusCode
        {
            get
            {
                return this._StatusCode;
            }
            set
            {
                this.OnStatusCodeChanging(value);
                this.ReportPropertyChanging("StatusCode");
                this._StatusCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StatusCode");
                this.OnStatusCodeChanged();
            }
        }
        private global::System.Nullable<int> _StatusCode;
        partial void OnStatusCodeChanging(global::System.Nullable<int> value);
        partial void OnStatusCodeChanged();
        /// <summary>
        /// There are no comments for IsCurrentOf in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Artist_0", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Artist> IsCurrentOf
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Artist>("lastFMcacheModel.FK_Artist_0", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Artist>("lastFMcacheModel.FK_Artist_0", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OfArtist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_TopTracksList_0", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Artist OfArtist
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_TopTracksList_0", "Artist").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_TopTracksList_0", "Artist").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OfArtist in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Artist> OfArtistReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_TopTracksList_0", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Artist>("lastFMcacheModel.FK_TopTracksList_0", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TopTracks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_TopTracks_1", "TopTracks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TopTracks> TopTracks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TopTracks>("lastFMcacheModel.FK_TopTracks_1", "TopTracks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TopTracks>("lastFMcacheModel.FK_TopTracks_1", "TopTracks", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for lastFMcacheModel.Track in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TrackID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="lastFMcacheModel", Name="Track")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Track : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Track object.
        /// </summary>
        /// <param name="trackID">Initial value of TrackID.</param>
        /// <param name="fullTitle">Initial value of FullTitle.</param>
        /// <param name="lowercaseTitle">Initial value of LowercaseTitle.</param>
        public static Track CreateTrack(int trackID, string fullTitle, string lowercaseTitle)
        {
            Track track = new Track();
            track.TrackID = trackID;
            track.FullTitle = fullTitle;
            track.LowercaseTitle = lowercaseTitle;
            return track;
        }
        /// <summary>
        /// There are no comments for Property TrackID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TrackID
        {
            get
            {
                return this._TrackID;
            }
            set
            {
                this.OnTrackIDChanging(value);
                this.ReportPropertyChanging("TrackID");
                this._TrackID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TrackID");
                this.OnTrackIDChanged();
            }
        }
        private int _TrackID;
        partial void OnTrackIDChanging(int value);
        partial void OnTrackIDChanged();
        /// <summary>
        /// There are no comments for Property FullTitle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FullTitle
        {
            get
            {
                return this._FullTitle;
            }
            set
            {
                this.OnFullTitleChanging(value);
                this.ReportPropertyChanging("FullTitle");
                this._FullTitle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FullTitle");
                this.OnFullTitleChanged();
            }
        }
        private string _FullTitle;
        partial void OnFullTitleChanging(string value);
        partial void OnFullTitleChanged();
        /// <summary>
        /// There are no comments for Property LowercaseTitle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LowercaseTitle
        {
            get
            {
                return this._LowercaseTitle;
            }
            set
            {
                this.OnLowercaseTitleChanging(value);
                this.ReportPropertyChanging("LowercaseTitle");
                this._LowercaseTitle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LowercaseTitle");
                this.OnLowercaseTitleChanged();
            }
        }
        private string _LowercaseTitle;
        partial void OnLowercaseTitleChanging(string value);
        partial void OnLowercaseTitleChanged();
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Track_1", "Artist")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Artist Artist
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_Track_1", "Artist").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_Track_1", "Artist").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Artist in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Artist> ArtistReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Artist>("lastFMcacheModel.FK_Track_1", "Artist");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Artist>("lastFMcacheModel.FK_Track_1", "Artist", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for RefSimilarTrackOf in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarTrack_0", "SimilarTrack")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarTrack> RefSimilarTrackOf
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarTrack>("lastFMcacheModel.FK_SimilarTrack_0", "SimilarTrack");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarTrack>("lastFMcacheModel.FK_SimilarTrack_0", "SimilarTrack", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for SimilarTrackLists in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_SimilarTrackList_0", "SimilarTrackList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SimilarTrackList> SimilarTrackLists
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SimilarTrackList>("lastFMcacheModel.FK_SimilarTrackList_0", "SimilarTrackList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SimilarTrackList>("lastFMcacheModel.FK_SimilarTrackList_0", "SimilarTrackList", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for CurrentSimilarTrackList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_Track_0", "SimilarTrackList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SimilarTrackList CurrentSimilarTrackList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_Track_0", "SimilarTrackList").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_Track_0", "SimilarTrackList").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CurrentSimilarTrackList in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SimilarTrackList> CurrentSimilarTrackListReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_Track_0", "SimilarTrackList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SimilarTrackList>("lastFMcacheModel.FK_Track_0", "SimilarTrackList", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TopTracks in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("lastFMcacheModel", "FK_TopTracks_0", "TopTracks")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TopTracks> TopTracks
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TopTracks>("lastFMcacheModel.FK_TopTracks_0", "TopTracks");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TopTracks>("lastFMcacheModel.FK_TopTracks_0", "TopTracks", value);
                }
            }
        }
    }
}
