  if(EigenVersion EQUAL 3)
    message("Using Eigen v3")
    add_definitions(-DEIGEN3)
    include_directories("C:/Program Files (Custom)/eigen")
  elseif(EigenVersion EQUAL 2)
    message("Using Eigen v2")
    add_definitions(-DEIGEN2)
    include_directories("C:/Program Files (Custom)/eigen2")
  else()
    message(FATAL_ERROR "Invalid Eigen version.")
  endif()
  
  set(build_suffix ${EigenVersion})
  if(EigenVectorize)
  	set(build_suffix "${build_suffix}v")
    remove_definitions(-DEIGEN_DONT_VECTORIZE)
  else()
    add_definitions(-DEIGEN_DONT_VECTORIZE)
  endif()
