message("Using Eigen v3")
add_definitions(-DEIGEN3)
message($ENV{EIGEN3_DIR})
include_directories($ENV{EIGEN3_DIR})
  
if(EigenVectorize)
	set(build_suffix "V")
	remove_definitions(-DEIGEN_DONT_VECTORIZE)
else()
	set(build_suffix "NV")
	add_definitions(-DEIGEN_DONT_VECTORIZE)
endif()
