  if(EigenVersion EQUAL 3)
    message("Using Eigen v3")
    add_definitions(-DEIGEN3)
    message($ENV{EIGEN3_DIR})
    if(IS_DIRECTORY "$ENV{EIGEN3_DIR}")
		include_directories($ENV{EIGEN3_DIR})
	else()
		message("eigen3 fallback")
        include_directories("C:/Program Files (Custom)/eigen")
    endif()
  elseif(EigenVersion EQUAL 2)
    message("Using Eigen v2")
    add_definitions(-DEIGEN2)
    include_directories("C:/Program Files (Custom)/eigen2")
  else()
    message(FATAL_ERROR "Invalid Eigen version.")
  endif()
  
  if(EigenVectorize)
  	set(build_suffix "V")
    remove_definitions(-DEIGEN_DONT_VECTORIZE)
  else()
  	set(build_suffix "NV")
    add_definitions(-DEIGEN_DONT_VECTORIZE)
  endif()
